### ISSUE TITLE
Enhanced ability to subset dataSet in the preprocessing routines

### ISSUE THREAD

**Issue by vanroekel** [pwolfram/mpas_xarray#12]
While building the sst_climo comparison script a need arose to subselect from 3-D fields (e.g. temperature).  A PR was put in to change this (#11), but it seems further functionality may be useful, e.g. selecting a set of times or cells.

**Comment by pwolfram** [comment]
See discussion in https://github.com/pwolfram/mpas_xarray/pull/11
