### ISSUE TITLE
Simplifying interface to preprocess_mpas*

### ISSUE THREAD

**Issue by pwolfram** [pwolfram/mpas_xarray#14]
`preprocess_mpas_timeSeriesStats` and `preprocess_mpas` are essentially identical functions and could readily be combined, e.g., via a flag like `timeSeriesStats=True`.  What will differ based on this flag is selection between about two lines of code to designate `datetimes`.  This will simplify and clarify the code and its usage.

cc @milenaveneziani for comments on this simplification / clarification

**Comment by pwolfram** [comment]
also, cc @vanroekel for discussion

**Comment by milenaveneziani** [comment]
@pwolfram: yes, that would be a good idea. Mind you that, at some point down the line, we should be able to make the two routines even more similar, when the timeSeriesStats AM for _both_ ocean and ice will have xtime_start and xtime_end in their output files. For now, this is only true for mpas-o, which is the reason why I haven't changed anything in preprocess_timeSeriesStats (leaving the calculation of datetime based on daysSinceStartOfSim).

**Comment by pwolfram** [comment]
@milenaveneziani, sounds great.  I'll submit a PR shortly for your review.

**Comment by pwolfram** [comment]
Here it is: https://github.com/pwolfram/mpas_xarray/pull/15

**Comment by pwolfram** [comment]
Note @milenaveneziani, if you point me to the right location I can also run and test this too before you test and sign off on it.

**Comment by pwolfram** [comment]
Closing based on #15.  Also, @milenaveneziani, do we need an issue for

> at some point down the line, we should be able to make the two routines even more similar, when the timeSeriesStats AM for both ocean and ice will have xtime_start and xtime_end in their output files. For now, this is only true for mpas-o, which is the reason why I haven't changed anything in preprocess_timeSeriesStats (leaving the calculation of datetime based on daysSinceStartOfSim).

to keep track of what needs to be done long term?

**Comment by milenaveneziani** [comment]
yes, @pwolfram, that sounds like a good idea. thanks.

**Comment by pwolfram** [comment]
@milenaveneziani, please see https://github.com/pwolfram/mpas_xarray/issues/18 to make sure this appropriately addresses this issue.
